### ISSUE TITLE
Doesn't unpack with ExtractTo

### ISSUE THREAD

**Issue by UQuark** [geoffsmith82/d7zip#6]
All files have zero size!

`  
   with CreateInArchive(CLSID_CFormat7z) do
   begin
     OpenFile('arch.7z');
     ExtractTo('C:\Users\artem\AppData\Roaming\test');
   end;
`

**Comment by danielmarschall** [comment]
(I can't reproduce this issue)

**Comment by UQuark** [comment]
IIRC, the problem was an LZMA2 archive, which is unsupported
