### ISSUE TITLE
Add support RAR5

### ISSUE THREAD

**Issue by grig27** [geoffsmith82/d7zip#7]
Please, add support RAR5 format.

  CLSID_CFormatRar5      : TGUID = '{23170F69-40C1-278A-1000-000110CC0000}'; // rar r00

And new binary files.

**Comment by MrLee73** [comment]
yes, it's work, thanks

**Comment by MrLee73** [comment]
i add this
CLSID_CFormatRar5 : TGUID = '{23170F69-40C1-278A-1000-000110CC0000}'; // rar r00

and it's work for extract new rar

**Comment by geoffsmith82** [comment]
I have added a list of the Guids I found in the documentation for the supported formats that were not in the file.  The dll's have been updated as well.
